const express = require('express');
const router = express.Router();
const user = require('./user.route.js');
const used_technology = require('./used_technology.route.js');
const technology_category = require('./technology_category.route.js');
const project_category = require('./project_category.route.js');
const project = require('./project.route.js');
const post_save = require('./post_save.route.js');
const post_photo = require('./post_photo.route.js');
const post_like = require('./post_like.route.js');
const post_comment = require('./post_comment.route.js');
const post = require('./post.route.js');
const message_photo = require('./message_photo.route.js');
const message = require('./message.route.js');
const location = require('./location.route.js');
const language = require('./language.route.js');
const comment_like = require('./comment_like.route.js');
const auth = require('./auth.route.js');
const admin = require('./admin.route.js');

router.use('/user', user);
router.use('/usedTechnology', used_technology);
router.use('/technologyCategory', technology_category);
router.use('/projectCategory', project_category);
router.use('/project', project);
router.use('/postSave', post_save);
router.use('/postPhoto', post_photo);
router.use('/postLike', post_like);
router.use('/postComment', post_comment);
router.use('/post', post);
router.use('/messagePhoto', message_photo);
router.use('/message', message);
router.use('/location', location);
router.use('/language', language);
router.use('/commentLike', comment_like);
router.use('/auth', auth);
router.use('/admin', admin);

module.exports = router;
